# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 08ae9ce49227ed976e5f5005571b59a9946885cf6c9940768fedb81c0b3f6ca71689a57c442d5080c0924897f689c76e3e155d5f9cbac3c31233e331f2d1ee52

test:
  secret_key_base: d963733a6488574513f893cf6364a8d9a313ae88876e1aef44a1d07cd1ce48edfd920e35324b4e774fc4d6fbf3fe59bd8f2183387487966fc4c308478674fb56

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
